services:
  tor:
    build:
      context: ./tor
      args:
        BLESK_TOR_VERSION:
        BLESK_TOR_USERNAME:
        BLESK_TOR_UID:
        BLESK_TOR_GID:
        BLESK_TOR_HOME:
        BLESK_TOR_ONIONS:
    restart: always
    stop_grace_period: 1m
    logging: &logging
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    env_file:
      - ./.env
    volumes:
      - data-tor:${BLESK_TOR_HOME}
    networks:
      internal:
        ipv6_address: ${BLESK_TOR_IPV6}
        ipv4_address: ${BLESK_TOR_IPV4}
    expose:
      - ${BLESK_TOR_PORT_SOCKS}
      - ${BLESK_TOR_PORT_CONTROL}
  bitcoincore:
    build:
      context: ./bitcoincore
      args:
        BLESK_BITCOINCORE_VERSION:
        BLESK_BITCOINCORE_USERNAME:
        BLESK_BITCOINCORE_UID:
        BLESK_BITCOINCORE_GID:
        BLESK_BITCOINCORE_HOME:
        BLESK_BITCOINCORE_RPC_USER:
        BLESK_BITCOINCORE_RPC_PASSWORD:
        BLESK_TOR_USERNAME:
        BLESK_TOR_GID:
    restart: always
    stop_grace_period: 1m
    logging: *logging
    env_file:
      - ./.env
    volumes:
      - data-bitcoincore:${BLESK_BITCOINCORE_HOME}/.bitcoin
      - data-tor:${BLESK_TOR_HOME}
    networks:
      internal:
        ipv6_address: ${BLESK_BITCOINCORE_IPV6}
        ipv4_address: ${BLESK_BITCOINCORE_IPV4}
    expose:
      - ${BLESK_BITCOINCORE_PORT_RPC}
      - ${BLESK_BITCOINCORE_PORT_P2P}
      - ${BLESK_BITCOINCORE_PORT_ZMQ_BLOCK}
      - ${BLESK_BITCOINCORE_PORT_ZMQ_TX}
    depends_on:
      - tor
  electrs:
    build:
      context: ./electrs
      args:
        BLESK_ELECTRS_VERSION:
        BLESK_ELECTRS_USERNAME:
        BLESK_ELECTRS_UID:
        BLESK_ELECTRS_GID:
        BLESK_ELECTRS_HOME:
    restart: always
    stop_grace_period: 1m
    logging: *logging
    env_file:
      - ./.env
    volumes:
      - data-electrs:${BLESK_ELECTRS_HOME}
    networks:
      internal:
        ipv6_address: ${BLESK_ELECTRS_IPV6}
        ipv4_address: ${BLESK_ELECTRS_IPV4}
    expose:
      - ${BLESK_ELECTRS_PORT}
    depends_on:
      - bitcoincore
  explorer:
    build:
      context: ./explorer
      args:
        BLESK_EXPLORER_VERSION:
        BLESK_EXPLORER_CHECKSUM:
        BLESK_EXPLORER_USERNAME:
        BLESK_EXPLORER_UID:
        BLESK_EXPLORER_GID:
        BLESK_EXPLORER_HOME:
    restart: always
    stop_grace_period: 1m
    logging: *logging
    env_file:
      - ./.env
    networks:
      internal:
        ipv6_address: ${BLESK_EXPLORER_IPV6}
        ipv4_address: ${BLESK_EXPLORER_IPV4}
    expose:
      - ${BLESK_EXPLORER_PORT}
    depends_on:
      - bitcoincore
      - electrs
  mariadb:
    build:
      context: ./mariadb
      args:
        BLESK_DOJO_VERSION:
        BLESK_MARIADB_SCRIPTS_CHECKSUM_1:
        BLESK_MARIADB_SCRIPTS_CHECKSUM_2:
        BLESK_MARIADB_VERSION:
    restart: always
    stop_grace_period: 1m
    logging: *logging
    env_file:
      - ./.env
    volumes:
      - data-mariadb:/var/lib/mysql
    networks:
      internal:
        ipv6_address: ${BLESK_MARIADB_IPV6}
        ipv4_address: ${BLESK_MARIADB_IPV4}
    expose:
      - ${BLESK_MARIADB_PORT}

volumes:
  data-tor:
  data-bitcoincore:
  data-electrs:
  data-mariadb:

networks:
  internal:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: ${BLESK_NET_INTERNAL_IPV6}
        - subnet: ${BLESK_NET_INTERNAL_IPV4}
