services:
  _svc: &svc
    container_name: svc
    image: blesk/svc
    pull_policy: never
    build:
      context: _svc
    read_only: true
    restart: always
    stop_grace_period: 1m
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    env_file:
      - ./.env
    networks:
      internal:

  init:
    container_name: init
    image: gcr.io/distroless/base-debian13:debug
    pull_policy: weekly
    read_only: true
    restart: no
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    network_mode: none
    volumes:
      - cookies:${BLESK_DIR_COOKIES}
    command:
      - -euc
      - |
        mkdir -p "${BLESK_TOR_DIR_COOKIE}"
        chown -R nonroot:nonroot "${BLESK_TOR_DIR_COOKIE}"
        mkdir -p "${BLESK_BITCOINCORE_DIR_COOKIE}"
        chown -R nonroot:nonroot "${BLESK_BITCOINCORE_DIR_COOKIE}"

  tor:
    <<: *svc
    container_name: tor
    image: blesk/tor
    build:
      context: ./tor
      args:
        BLESK_TOR_VERSION: "${BLESK_TOR_VERSION}"
    command:
      - --SocksPort
      - >-
        [${BLESK_TOR_NET_ADDRESS}]:${BLESK_TOR_NET_PORT_SOCKS} OnionTrafficOnly ExtendedErrors
      - --SocksPolicy
      - accept6 ${BLESK_NET_INTERNAL}
      - --DataDirectory
      - ${BLESK_DIR_HOME}/.tor
      - --ControlPort
      - >-
        [${BLESK_TOR_NET_ADDRESS}]:${BLESK_TOR_NET_PORT_CONTROL}
      - --CookieAuthFile
      - ${BLESK_TOR_DIR_COOKIE}/control_auth_cookie
    volumes:
      - tor:${BLESK_DIR_HOME}
      - cookies:${BLESK_DIR_COOKIES}
    networks:
      internal:
        ipv6_address: ${BLESK_TOR_NET_ADDRESS}
      external:
    depends_on:
      init:
        condition: service_completed_successfully

  bitcoincore:
    <<: *svc
    container_name: bitcoincore
    image: blesk/bitcoincore
    build:
      context: ./bitcoincore
      args:
        BLESK_BITCOINCORE_VERSION: "${BLESK_BITCOINCORE_VERSION}"
    command:
      - --conf=/etc/bitcoincore/bitcoin.conf
      - --whitelist=${BLESK_NET_INTERNAL}
      - --bind=${BLESK_BITCOINCORE_NET_ADDRESS}
      - --port=${BLESK_BITCOINCORE_NET_PORT_P2P}
      - --proxy=[${BLESK_TOR_NET_ADDRESS}]:${BLESK_TOR_NET_PORT_SOCKS}
      - --maxconnections=${BLESK_BITCOINCORE_MAX_CONNECTIONS}
      - --maxuploadtarget=${BLESK_BITCOINCORE_MAX_UPLOAD_TARGET}
      - --zmqpubrawblock=tcp://[${BLESK_BITCOINCORE_NET_ADDRESS}]:${BLESK_BITCOINCORE_NET_PORT_ZMQ_BLOCK}
      - --zmqpubrawtx=tcp://[${BLESK_BITCOINCORE_NET_ADDRESS}]:${BLESK_BITCOINCORE_NET_PORT_ZMQ_TX}
      - --rpcallowip=${BLESK_NET_INTERNAL}
      - --rpcbind=${BLESK_BITCOINCORE_NET_ADDRESS}
      - --rpcport=${BLESK_BITCOINCORE_NET_PORT_RPC}
      - --rpccookiefile=${BLESK_BITCOINCORE_COOKIE}
      - --rpccookieperms=group
      - --nosettings
      # only for initial blocks sync
      # - --blocksonly=1
      # - --dbcache="${BLESK_BITCOINCORE_DB_CACHE}"
    volumes:
      - bitcoincore:${BLESK_DIR_HOME}
      - cookies:${BLESK_DIR_COOKIES}
    networks:
      internal:
        ipv6_address: ${BLESK_BITCOINCORE_NET_ADDRESS}
    depends_on:
      init:
        condition: service_completed_successfully
      tor:
        condition: service_started

  electrs:
    <<: *svc
    container_name: electrs
    image: blesk/electrs
    build:
      context: ./electrs
      args:
        BLESK_ELECTRS_VERSION: "${BLESK_ELECTRS_VERSION}"
        BLESK_ELECTRS_SSH_KEY_FINGERPRINT: "${BLESK_ELECTRS_SSH_KEY_FINGERPRINT}"
    command:
      - --db-dir
      - ${BLESK_DIR_HOME}/db
      - --cookie-file
      - ${BLESK_BITCOINCORE_COOKIE}
      - --electrum-rpc-addr
      - ${BLESK_ELECTRS_NET_ADDRESS}:${BLESK_ELECTRS_NET_PORT}
      - --daemon-rpc-addr
      - bitcoincore:${BLESK_BITCOINCORE_NET_PORT_RPC}
      - --daemon-p2p-addr
      - bitcoincore:${BLESK_BITCOINCORE_NET_PORT_P2P}
      - --index-batch-size
      - ${BLESK_ELECTRS_BATCH_SIZE}
      - --index-lookup-limit
      - ${BLESK_ELECTRS_LOOKUP_LIMIT}
      - --log-filters
      - INFO
    volumes:
      - electrs:${BLESK_DIR_HOME}
      - cookies:${BLESK_DIR_COOKIES}
    read_only: false
    networks:
      internal:
        ipv6_address: ${BLESK_ELECTRS_NET_ADDRESS}
    depends_on:
      bitcoincore:
        condition: service_started
        restart: true

  explorer:
    <<: *svc
    container_name: explorer
    image: blesk/explorer
    build:
      context: ./explorer
      args:
        BLESK_DIR_HOME: "${BLESK_DIR_HOME}"
        BLESK_EXPLORER_VERSION: "${BLESK_EXPLORER_VERSION}"
        BLESK_EXPLORER_CHECKSUM: "${BLESK_EXPLORER_CHECKSUM}"
    command:
      - --host
      - ${BLESK_EXPLORER_NET_ADDRESS}
      - --port
      - ${BLESK_EXPLORER_NET_PORT}
      - --bitcoind-port
      - ${BLESK_BITCOINCORE_NET_PORT_RPC}
      - --bitcoind-cookie
      - ${BLESK_BITCOINCORE_COOKIE}
      - --electrum-servers
      - tcp://electrs:${BLESK_ELECTRS_NET_PORT}
      - --slow-device-mode
      - ${BLESK_EXPLORER_SLOW_DEVICE_MODE}
      - --filesystem-cache-dir
      - ${BLESK_EXPLORER_CACHE_DIR}
    volumes:
      - cookies:${BLESK_DIR_COOKIES}:ro
      - type: tmpfs
        target: ${BLESK_EXPLORER_CACHE_DIR}
        tmpfs:
          size: 1M
          mode: 0777
    networks:
      internal:
        ipv6_address: ${BLESK_EXPLORER_NET_ADDRESS}
    depends_on:
      bitcoincore:
        condition: service_started
      electrs:
        condition: service_started

volumes:
  cookies:
  tor:
  bitcoincore:
  electrs:

networks:
  external: &network
    driver: bridge
    enable_ipv6: true
    enable_ipv4: false
  internal:
    <<: *network
    internal: true
    ipam:
      config:
        - subnet: ${BLESK_NET_INTERNAL}
