worker_processes auto;
pid /tmp/nginx.pid;

events {
  worker_connections 768;
}

http {
  proxy_temp_path /tmp/proxy_temp;
  client_body_temp_path /tmp/client_temp;
  fastcgi_temp_path /tmp/fastcgi_temp;
  uwsgi_temp_path /tmp/uwsgi_temp;
  scgi_temp_path /tmp/scgi_temp;

  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  # Disable activity logging for privacy.
  access_log  off;

  # Do not reveal the version of server
  server_tokens  off;

  sendfile  on;

  keepalive_timeout  95;

  # Enable response compression
  gzip  on;
  # Compression level: 1-9
  gzip_comp_level  4;
  # Minimum length of response before gzip kicks in
  gzip_min_length  128;
  # Compress these MIME types in addition to text/html
  gzip_types  application/json application/javascript;
  # Help with proxying by adding the Vary: Accept-Encoding response
  gzip_vary  on;

  include  /etc/nginx/sites-enabled/*.conf;
}
